services:
  satisfactory:
    build: .
    container_name: satisfactory-arm64
    hostname: satisfactory-arm64
    restart: unless-stopped
    ports:
      - "7777:7777/tcp"
      - "7777:7777/udp"
      - "8888:8888/tcp"
    volumes:
      #      - "./steamcmd:/home/steam/steamcmd"
      - "./satisfactory-server:/config"
    environment:
      - MAXPLAYERS=4
      - SERVER_NAME=sss_world
      - SERVER_PASSWORD=${SERVER_PASSWORD}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}a
      - PGID=1000
      - PUID=1000
      - STEAMBETA=false
    deploy:
      resources:
        limits:
          memory: 20G
          cpus: '3.5'
        reservations:
          memory: 16G
          cpus: '2.5'
